// One-off script: scaffolds the MaidTrack TWA Android project using
// @bubblewrap/core directly, bypassing the interactive CLI wizard (all
// values are already known/decided, so there's nothing to ask a human).
// Not part of the app runtime — used once to generate android-twa/.
const path = require('path');
const fs = require('fs');
const { execFile } = require('child_process');
const util = require('util');
const execFilePromise = util.promisify(execFile);

const CORE_PATH = 'C:/Users/user31a/AppData/Roaming/npm/node_modules/@bubblewrap/cli/node_modules/@bubblewrap/core';
const { TwaManifest, TwaGenerator, ConsoleLog } = require(CORE_PATH);

const KEYTOOL_EXE = 'C:/Android/jdk17/jdk-17.0.20+8/bin/keytool.exe';

const targetDirectory = 'C:/Android/maidtrack-twa';
const manifestUrl = process.argv[2];
if (!manifestUrl) {
    console.error('Usage: node build_twa.js <manifest-url>');
    process.exit(1);
}

// The website's own manifest.json points at an emoji-rendered icon (the
// project owner wants the emoji as the website/PWA identity). The actual
// Android app icon should be the real logo instead — a separate file
// (assets/icons/apk-icon-*.png, generated by generate_icons.php from
// assets/logo-source.png) not referenced by manifest.json at all, only
// pulled in here for the APK build specifically.
const sitePath = manifestUrl.slice(0, manifestUrl.lastIndexOf('/'));
const apkIconUrl = `${sitePath}/assets/icons/apk-icon-512.png`;

(async () => {
    if (!fs.existsSync(targetDirectory)) fs.mkdirSync(targetDirectory, { recursive: true });

    const twaManifest = await TwaManifest.fromWebManifest(manifestUrl);
    twaManifest.packageId = 'com.maidtrack.app';
    twaManifest.iconUrl = apkIconUrl;
    twaManifest.maskableIconUrl = apkIconUrl;
    twaManifest.signingKey.path = path.join(targetDirectory, 'android.keystore');
    twaManifest.signingKey.alias = 'maidtrack';

    await twaManifest.saveToFile(path.join(targetDirectory, 'twa-manifest.json'));

    const twaGenerator = new TwaGenerator();
    const log = new ConsoleLog('Generating TWA');
    await twaGenerator.createTwaProject(targetDirectory, twaManifest, log, () => {});

    // Invoke keytool directly via its absolute path with execFile (no
    // shell, no PATH lookup at all) rather than Bubblewrap's own KeyTool
    // class — its PATH-based resolution proved unreliable on this machine
    // (Windows Node processes can carry duplicate 'PATH'/'Path' env keys
    // that confuse bare-command resolution in unpredictable ways).
    if (!fs.existsSync(twaManifest.signingKey.path)) {
        const dname = 'cn=MaidTrack Test, ou=Engineering, o=MaidTrack, c=MY';
        await execFilePromise(KEYTOOL_EXE, [
            '-genkeypair',
            '-dname', dname,
            '-alias', twaManifest.signingKey.alias,
            '-keypass', 'maidtrackTest2026',
            '-keystore', twaManifest.signingKey.path,
            '-storepass', 'maidtrackTest2026',
            '-validity', '20000',
            '-keyalg', 'RSA',
        ]);
        console.log('Signing key created at ' + twaManifest.signingKey.path);
    }

    console.log('DONE: project generated at ' + targetDirectory);
})().catch((e) => {
    console.error(e);
    process.exit(1);
});
